#!/bin/bash

# Generate the build script

xsltproc -v -o build utilities/build.xsl data/_pages.xml;

# Create the README file

xsltproc -v -o ../README.md utilities/readme.xsl data/_pages.xml;

# These commands will process HTML files with XSLT when you run `./build` inside the `workspace` directory.
# This list is dynamically generated as you add more pages to the `data/_pages.xml` file.

xsltproc -v -o ../index.html pages/index.xsl data/index.xml;
xsltproc -v -o ../community/index.html pages/community.xsl data/community.xml;
xsltproc -v -o ../community/post/index.html pages/community_post.xsl data/community_post.xml;
