#!/bin/bash

# Generate the build script

xsltproc -v -o build utilities/build.xsl data/_pages.xml;

# Create the README file

xsltproc -v -o ../README.md utilities/readme.xsl data/_pages.xml;

# These commands will process HTML files with XSLT when you run `./build` inside the `workspace` directory.
# This list is dynamically generated as you add more pages to the `data/_pages.xml` file.

xsltproc -v -o ../index.html pages/index.xsl data/index.xml;
xsltproc -v -o ../docs/index.html pages/index.xsl data/docs.xml;
xsltproc -v -o ../intro/index.html pages/docs_intro.xsl data/docs_intro.xml;
xsltproc -v -o ../concepts/index.html pages/docs_concepts.xsl data/docs_concepts.xml;
xsltproc -v -o ../workflows/index.html pages/docs_workflows.xsl data/docs_workflows.xml;
xsltproc -v -o ../projects/index.html pages/docs_projects.xsl data/docs_projects.xml;
xsltproc -v -o ../api/index.html pages/docs_api.xsl data/docs_api.xml;
