#!/bin/bash

# Generate the build script

xsltproc -v -o build utilities/build.xsl data/_pages.xml;

# Create the README file

xsltproc -v -o ../README.md utilities/readme.xsl data/_pages.xml;

# These commands will process HTML files with XSLT when you run `./build` inside the `workspace` directory.
# This list is dynamically generated as you add more pages to the `data/_pages.xml` file.

xsltproc -v -o ../index.html pages/index.xsl data/index.xml;
xsltproc -v -o ../discussions/index.html pages/discussions.xsl data/discussions.xml;
xsltproc -v -o ../discussions/post/index.html pages/discussions_post.xsl data/discussions_post.xml;
